config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'coupons/index'

  namespace :admin, path: "asdfe" do
    get 'dashboard/index'
    resources :books, except: [:show]
    resources :coupons, except: [:show]
  end

  resources :books, only: [:index]
  resources :orders, only: [:create]

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
    member do
      post 'apply_coupon', to: 'carts#apply_coupon'
      delete 'cancel_coupon', to: 'carts#cancel_coupon'
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :order_books
  has_many :orders, through: :order_books
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :find_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to admin_books_path, notice: "新增成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to admin_books_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path, notice: "已刪除"
  end

  private
  def find_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :price)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/admin/books/_form.html.erb
<div class="my-5">
  <%= form.label :title %>
  <%= form.text_field :title, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div class="my-5">
  <%= form.label :price %>
  <%= form.text_field :price, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

<div class="inline">
  <% if @book.new_record? %>
    <%= form.submit "建立書籍", class: "add-btn" %>
  <% else %>
    <%= form.submit "更新", class: "add-btn" %>
  <% end %>
</div>

app/views/admin/books/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= form_with(model: @book, url: admin_book_path(@book), method: :patch, data: { turbo: false }) do |form| %>
      <h1 class="text-4xl font-bold">編輯書籍</h1>

      <%= render "form", form: form %>
  <% end %>
</div>

app/views/admin/books/index.html.erb
<div class="container mx-auto">  
  <%= link_to 'Back to Dashboard', admin_dashboard_index_path, class: "save-btn mb-5" %>
  <div class="flex flex-col items-center mb-4 md:flex-row">
    <%= link_to "新增書籍", new_admin_book_path, class: "add-btn mb-2 md:mb-0" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full table-auto">
      <thead class="text-lg font-semibold">
        <tr>
          <th class="py-5 pr-5 text-left">書籍名稱</th>
          <th class="py-5 pr-5 text-left">書籍售價</th>
          <th class="py-5"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td>NT $<%= book.price %></td>
            <td class="flex items-center justify-center pt-1">
              <%= link_to '編輯', edit_admin_book_path(book), class: "save-btn text-xs mr-2" %>
              <%= button_to "刪除", admin_book_path(book), method: :delete, data: { confirm: "確定刪除?" }, class: "danger-btn text-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/books/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= form_with(model: @book, url: admin_books_path, data: { turbo: false }) do |form| %>
    <h1 class="text-4xl font-bold">新增書籍</h1>
    <%= render "form", form: form %>
  <% end %>
</div>