config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'coupons/index'

  namespace :admin, path: "asdfe" do
    get 'dashboard/index'
    resources :books, except: [:show]
    resources :coupons, except: [:show]
  end

  resources :books, only: [:index]
  resources :orders, only: [:create]

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
    member do
      post 'apply_coupon', to: 'carts#apply_coupon'
      delete 'cancel_coupon', to: 'carts#cancel_coupon'
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :order_books
  has_many :orders, through: :order_books
end

app/controllers/admin/books_controller.rb
class Admin::BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :find_book, only: [:edit, :update, :destroy]

  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to admin_books_path, notice: "新增成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to admin_books_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to admin_books_path, notice: "已刪除"
  end

  private
  def find_book
    @book = Book.find_by(id: params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :price)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  def index
    @books = Book.all
  end
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/views/books/index.html.erb
<div class="container mx-auto">  
  <div class="flex flex-col items-center mb-4 md:flex-row">
    <%= link_to "購物車", cart_path, class: "save-btn ml-2" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full table-auto">
      <thead class="text-lg font-semibold">
        <tr>
          <th class="py-5 pr-5 text-left">書籍名稱</th>
          <th class="py-5 pr-5 text-left">書籍售價</th>
          <th class="py-5"></th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td><%= book.title %></td>
            <td>NT $<%= book.price %></td>
            <td class="pr-5 md:pr-10">
              <%= link_to "選購", add_cart_path(book), data: { turbo_method: :post }, class: "add-btn font-semibold" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>