config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'coupons/index'

  namespace :admin, path: "asdfe" do
    get 'dashboard/index'
    resources :books, except: [:show]
    resources :coupons, except: [:show]
  end

  resources :books, only: [:index]
  resources :orders, only: [:create]

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
    member do
      post 'apply_coupon', to: 'carts#apply_coupon'
      delete 'cancel_coupon', to: 'carts#cancel_coupon'
    end
  end
end

app/models/cart.rb
class Cart
  attr_reader :items, :coupon

  def initialize(items = [])
    @items = items
    @coupon = nil
  end

  def add_item(book_id)
    found_item = items.find { |item| item.book_id == book_id }
  
    if found_item
      found_item.increment
    else
      @items << CartItem.new(book_id)
    end
  end

  def empty?
    @items.empty?
  end

  def apply_coupon(coupon)
    if coupon.discount_amount <= total_price
      @coupon = coupon
    else
      @coupon = nil
    end
  end

  def total_price
    total = items.sum(&:price)
    if coupon
      total -= coupon.discount_amount
    end
    total
  end

  def serialize
    all_items = items.map { |item|
      { "book_id" => item.book_id, "quantity" => item.quantity }
    }

    { "items" => all_items }
  end

  def self.transfer_hash(hash)
    if hash.nil?
      new []
    else
      new hash["items"].map { |item_hash|
        CartItem.new(item_hash["book_id"], item_hash["quantity"])
      }
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    @coupon = Coupon.all
  end

  def apply_coupon
    coupon_id = params[:coupon_id]

    @coupon = Coupon.all

    selected_coupon = @coupon.find { |coupon| coupon.id.to_s == coupon_id }

    if selected_coupon.present?
      session[:selected_coupon] = selected_coupon
    end

    redirect_to cart_path(params[:id])
  end

  def cancel_coupon
    session[:selected_coupon] = nil
    redirect_to cart_path(params[:id])
  end

  def add
    @cart.add_item(params[:id])
    session[:order_info] = @cart.serialize

    redirect_to books_path, notice: "已加入購物車"
  end

  def destroy
    session[:order_info] = nil
    session[:selected_coupon] = nil
    redirect_to books_path, notice: "購物車已清空"
  end
end

app/views/carts/show.html.erb
<div class="w-full mx-auto md:w-2/3">
  <div class="flex flex-col items-center md:flex-row md:justify-between">
    <h1 class="mb-5 text-4xl font-bold md:mb-0">購物車</h1>
    <div class="flex space-x-5">
      <% if @cart.items.any? %>
        <%= link_to '選取您的優惠券', coupons_index_path, class: "add-btn" %>
        <%= link_to '繼續選購', books_path, class: "danger-btn" %>
      <% else %>
        <%= link_to '立即選購', books_path, class: "danger-btn" %>
      <% end %>
    </div>
  </div>
  <table class="w-full mt-5">
    <thead class="text-lg font-semibold">
      <tr>
        <th class="py-3 pr-3 text-left md:pr-5">書籍名稱</th>
        <th class="py-3 pr-3 text-left md:pr-5">數量</th>
        <th class="py-3 pr-3 text-left md:pr-5">單價</th>
        <th class="py-3 pr-3 text-left md:pr-5">小計</th>
      </tr>
    </thead>
    <tbody>
      <% @cart.items.each do |item| %>
        <tr>
          <td class="text-left"><%= item.book.title %></td>
          <td class="text-left"><%= item.quantity %></td>
          <td class="text-left md:pr-5">NT $<%= item.book.price %></td>
          <td class="text-left">NT $<%= item.price %></td>
        </tr>
      <% end %>
    </tbody>
    <tfoot class="border-t border-gray-300">
      <tr class="text-lg font-semibold">
        <td colspan="3">總計</td>
        <% if session[:selected_coupon].present? %>
          <% selected_coupon = session[:selected_coupon] %>
          <% discount_amount = selected_coupon["discount_amount"] %>
          <% total_price_after_discount = @cart.total_price - discount_amount %>
          <td class="text-left">NT $<%= total_price_after_discount %></td>
        <% else %>
          <td class="text-left">NT $<%= @cart.total_price %></td>
        <% end %>
      </tr>
      <% if session[:selected_coupon].present? %>
        <tr>
          <td class="pt-10">已套用優惠券: <%= selected_coupon["name"] %></td>
          <td class="pt-10"><%= button_to '取消此優惠券', cancel_coupon_cart_path, method: :delete, data: { turbo: false }, class: 'save-btn text-sm' %></td>
        </tr>
      <% end %>
    </tfoot>
  </table>
  <%= link_to "清空購物車", cart_path, data: {turbo_method: :delete}, class: "danger-btn text-sm mt-5" %>
  <%= link_to "建立訂單", orders_path, data: {turbo_method: :post}, class: "save-btn" %>
</div>