config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#index'
  get 'coupons/index'

  namespace :admin, path: "asdfe" do
    get 'dashboard/index'
    resources :books, except: [:show]
    resources :coupons, except: [:show]
  end

  resources :books, only: [:index]
  resources :orders, only: [:create]

  resource :cart, only:[:show, :destroy] do
    collection do
      post :add, path:'add/:id'
    end
    member do
      post 'apply_coupon', to: 'carts#apply_coupon'
      delete 'cancel_coupon', to: 'carts#cancel_coupon'
    end
  end
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  validates :name, presence: true
  validates :discount_amount, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :expiration_date, presence: true
  validates :max_usage_count, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :used_count, presence: true, numericality: { less_than_or_equal_to: :max_usage_count }
  
  belongs_to :user
  has_many :user_coupons
  has_many :users, through: :user_coupons
end

app/controllers/admin/coupons_controller.rb
class Admin::CouponsController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_admin
  before_action :find_coupon, only: [:edit, :update, :destroy]

  def index
    @coupons = Coupon.all
  end

  def new
    @coupon = Coupon.new
  end

  def create
    @coupon = Coupon.new(coupon_params)
    if @coupon.save
      redirect_to admin_coupons_path, notice: "新增成功"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @coupon.update(coupon_params)
      redirect_to admin_coupons_path, notice: "更新成功"
    else
      render :edit
    end
  end

  def destroy
    @coupon.destroy
    redirect_to admin_coupons_path, notice: "已刪除"
  end

  private
  def find_coupon
    @coupon = Coupon.find_by(id: params[:id])
  end

  def coupon_params
    params.require(:coupon).permit(:name, :discount_amount, :expiration_date, :max_usage_count, :used_count, :is_used, :user_id)
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def index
    @coupon = Coupon.all
  end
end

app/helpers/admin/coupons_helper.rb
module Admin::CouponsHelper
end

app/views/admin/coupons/_form.html.erb
<div class="my-5">
  <%= form.label "優惠券名稱" %>
  <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div class="my-5">
  <%= form.label "折扣金額" %>
  <%= form.text_field :discount_amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div class="my-5">
  <%= form.label "最後使用日" %>
  <%= form.date_field :expiration_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div class="my-5">
  <%= form.label "可使用次數" %>
  <%= form.number_field :max_usage_count, in: 1.0..5.0, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>
<div><%= form.hidden_field :user_id, value: current_user.id %></div>
<div class="inline">
  <% if @coupon.new_record? %>
    <%= form.submit "建立優惠券", class: "add-btn" %>
  <% else %>
    <%= form.submit "更新", class: "add-btn" %>
  <% end %>
</div>

app/views/admin/coupons/edit.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= form_with(model: @coupon, url: admin_coupon_path(@coupon), method: :patch, data: { turbo: false }) do |form| %>
    <h1 class="text-4xl font-bold">編輯優惠券</h1>

    <%= render "form", form: form %>
  <% end %>
</div>

app/views/admin/coupons/index.html.erb
<div class="container mx-auto">
  <%= link_to 'Back to Dashboard', admin_dashboard_index_path, class: "save-btn mb-5" %>
  <div class="flex flex-col items-center mb-4 md:flex-row">
    <%= link_to "新增優惠券", new_admin_coupon_path, class: "add-btn mb-2 md:mb-0" %>
  </div>

  <div class="overflow-x-auto">
    <table class="min-w-full table-auto">
      <thead class="text-lg font-semibold">
        <tr>
          <th class="py-5 pr-5 text-left">優惠券名稱</th>
          <th class="py-5 pr-5 text-left">折扣金額</th>
          <th class="py-5 pr-5 text-left">最後使用日</th>
          <th class="py-5 pr-5 text-left">可使用次數</th>
          <th class="py-5 pr-5 text-left">目前使用次數</th>
        </tr>
      </thead>
      <tbody>
        <% @coupons.each do |coupon| %>
          <tr>
            <td><%= coupon.name %></td>
            <td><%= coupon.discount_amount %></td>
            <td><%= coupon.expiration_date %></td>
            <td><%= coupon.max_usage_count %></td>
            <td><%= coupon.used_count %></td>
            <td class="flex items-center justify-center pt-1">
              <%= link_to '編輯', edit_admin_coupon_path(coupon), class: "save-btn text-xs mr-2" %>
              <%= button_to "刪除", admin_coupon_path(coupon), method: :delete, data: { confirm: "確定刪除?" }, class: "danger-btn text-xs" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/coupons/new.html.erb
<div class="w-full mx-auto md:w-2/3">
  <%= form_with(model: @coupon, url: admin_coupons_path, data: { turbo: false }) do |form| %>
    <h1 class="text-4xl font-bold">新增優惠券</h1>

    <%= render "form", form: form %>
  <% end %>
</div>